plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.165'
}

tasks.named('wrapper', Wrapper).configure {
    // Define wrapper values here so as to not have to always do so when updating gradlew.properties.
    // Switching this to Wrapper.DistributionType.ALL will download the full gradle sources that comes with
    // documentation attached on cursor hover of gradle classes and methods. However, this comes with increased
    // file size for Gradle. If you do switch this to ALL, run the Gradle wrapper task twice afterwards.
    // (Verify by checking gradle/wrapper/gradle-wrapper.properties to see if distributionUrl now points to `-all`)
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id + "-" + minecraft_version
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)


runs {
    configureEach {
        workingDirectory project.file('runs_neoforge')
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        workingDirectory project.file('runs_data_neoforge')
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        // EMI
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        // REI
        url "https://maven.shedaniel.me/"
    }
    mavenLocal()
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {

    implementation "net.neoforged:neoforge:${neo_version}"
    implementation "curse.maven:jade-324717:${jade_id}"
    implementation "curse.maven:croptopia-415438:${croptopia_id}"
    implementation "curse.maven:farmers-delight-398521:${farmers_delight_id}"
    implementation "curse.maven:epherolib-885449:${ephero_lib_id}"

    localRuntime "curse.maven:appleskin-248787:${appleskin_id}"
    localRuntime "curse.maven:jei-238222:${jei_id}"

    localRuntime "curse.maven:enders-delight-827163:5879700"
    localRuntime "curse.maven:rustic-delight-1106612:6844406"
    localRuntime "curse.maven:seed-delight-1016377:5734731"
    localRuntime "curse.maven:oceans-delight-841262:5618115"
    localRuntime "curse.maven:crabbers-delight-892827:7084860"
    localRuntime "curse.maven:casualness-delight-909519:5853751"
    localRuntime "curse.maven:fruits-delight-943774:7041466" //still?? how are you breaking datagen in MY MOD
    localRuntime "curse.maven:brewin-and-chewin-637808:6631432"
    localRuntime "curse.maven:veggies-delight-1082807:7115024"
    localRuntime "curse.maven:miners-delight-plus-689630:6860679"
    localRuntime "curse.maven:lodestone-616457:6630047" //miners delight dependency
    localRuntime "curse.maven:my-nethers-delight-1003673:6938550"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            croptopia_range        : croptopia_range,
            fd_range               : fd_range
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}