org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.213
neo_version_range=[21.1.0-beta,)
loader_version_range=[4,)

mod_id=farmers_croptopia
mod_name=Farmer's Croptopia
mod_license=Apache
mod_version=3.2.0
mod_group_id=com.accbdd.farmers_croptopia
mod_authors=ACCBDD
mod_description=A compatibility addon between Croptopia and Farmer's Delight (and addons!)

# compat
jei_id = 5846880
jade_id = 5846105
fd_range = [1.2,)
farmers_delight_id = 6917256
croptopia_range = [3.0,)
croptopia_id = 5571647
ephero_lib_id = 5549595

# runtime testing
appleskin_id = 5586600

